[build]
  command = "cd frontend && yarn install && yarn build && cp -r build ../functions/public"
  functions = "functions"

[[redirects]]
  from = "/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200

[[redirects]]
  from = "/images/:imageName"
  to = "/.netlify/functions/images/:imageName"
  status = 200

[[redirects]]
  from = "/images"
  to = "/.netlify/functions/images"
  status = 200
